# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Da Wo0ki's Toybox
tagline:          'Randome stuff from around the net'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://dawookie.github.io

author:
  name:           'Rik Schneider'
  url:            https://twitter.com/the_fuzzy_one

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/dawookie/dawookie.github.io
